### ISSUE TITLE
Major D3FEND Ontology Changes

### ISSUE THREAD

**Issue by netfl0** [unibz-core/d3fend-analysis#2]
We've released a major upgrade to the D3FEND Ontology, 0.17.0, with a new D3FEND Core set of classes we intend to organize with the community. Once the upper-level classes are well defined we'll create a 1.0 release.

**Comment by italojsoliveira** [comment]
Thanks for this information. I will take a look at the new release of D3FEND. It is good to see that D3FEND has been evolving lively.
